use strict;
use warnings;

my $common_labels = {
    '-8 and -5' => {
        '-8' => 'NA LT 3 records',
        '-5' => 'NA Window/Grp B Record'
    },
    '-6' => {
        '-6' => 'Not applicable'
    },
    'yes or no' => {
        '0' => 'No',
        '1' => 'Yes'
    },
    'submission flags' => {
        '000' => 'Blk, Blk, Blk',
        '001' => 'Blk, Blk, Window',
        '010' => 'Blk, GrpAB, Blk',
        '011' => 'Blk, GrpAB, Window',
        '100' => 'Zero-rpt, Blk, Blk',
        '101' => 'Zero-rpt, Blk, Window',
        '110' => 'Zero-rpt, GrpAB, Blk',
        '111' => 'Zero-rpt, GrpAB, Window'
    },
    'FIPS' => {
        '900' => 'UCR',
        '-9' => 'Undetermined',
        '-6' => 'Not applicable'
    }
};

my $file_breakdown = {
    'segment' => {
        description => 'Incident-level extract file',
        position => 0,
        width => 2,
        possibilities => {
            '01' => 'Admin segment',
            '04' => 'Victim segment',
            '05' => 'Offender segment',
            '07' => 'Arrestee segment',
            'W1' => 'Window exceptional clearance segment',
            'W6' => 'Window arrest segment'
        }
    }, 'state code' => {
        description => 'Two-digit value assigned to the state',
        position => 2,
        width => 2,
        possibilities => {
            '01' => ['AL','Alabama'],
            '02' => ['AZ','Arizona'],
            '03' => ['AR','Arkansas'],
            '04' => ['CA','California'],
            '05' => ['CO','Colorado'],
            '06' => ['CT','Connecticut'],
            '07' => ['DE','Delaware'],
            '08' => ['DC','District of Columbia'],
            '09' => ['FL','Florida'],
            '10' => ['GA','Georgia'],
            '11' => ['ID','Idaho'],
            '12' => ['IL','Illinois'],
            '13' => ['IN','Indiana'],
            '14' => ['IA','Iowa'],
            '15' => ['KS','Kansas'],
            '16' => ['KY','Kentucky'],
            '17' => ['LA','Louisiana'],
            '18' => ['ME','Maine'],
            '19' => ['MD','Maryland'],
            '20' => ['MA','Massachusetts'],
            '21' => ['MI','Michigan'],
            '22' => ['MN','Minnesota'],
            '23' => ['MS','Mississippi'],
            '24' => ['MO','Missouri'],
            '25' => ['MT','Montana'],
            '26' => ['NB','Nebraska'],
            '27' => ['NV','Nevada'],
            '28' => ['NH','New Hampshire'],
            '29' => ['NJ','New Jersey'],
            '30' => ['NM','New Mexico'],
            '31' => ['NY','New York'],
            '32' => ['NC','North Carolina'],
            '33' => ['ND','North Dakota'],
            '34' => ['OH','Ohio'],
            '35' => ['OK','Oklahoma'],
            '36' => ['OR','Oregon'],
            '37' => ['PA','Pennsylvania'],
            '38' => ['RI','Rhode Island'],
            '39' => ['SC','South Carolinia'],
            '40' => ['SD','South Dakota'],
            '41' => ['TN','Tennessee'],
            '42' => ['TX','Texas'],
            '43' => ['UT','Utah'],
            '44' => ['VT','Vermont'],
            '45' => ['VA','Virginia'],
            '46' => ['WA','Washington'],
            '47' => ['WV','West Virginia'],
            '48' => ['WI','Wisconsin'],
            '49' => ['WY','Wyoming'],
            '50' => ['AK','Alaska'],
            '51' => ['HI','Hawaii'],
            '52' => ['CZ','Canal Zone'],
            '53' => ['PR','Puerto Rico'],
            '54' => ['AS','American Samoa'],
            '55' => ['GM','Guam'],
            '62' => ['VI','Virgin Islands']
        }
    }, 'originating agency identifier-ORI' => {
        description => 'The agency that is authorized to report crime data to the FBI',
        position => 4,
        width => 9,
        possibilites => {}
    }, 'incident number' => {
        description => 'Unqiue case number assigned to the incident by the agency',
        position => 13,
        width => 12,
        possibilities => {}
    }, 'incident date' => {
        description => 'YYYYMMDD date of incident',
        position => 25,
        width => 8,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'batch header 1 records per ORI-incident number' => {
        description => 'Batch number 1 of 3 (b1) in a group of records with a common ORI and incident number',
        position => 33,
        width => 3,
        possibilities => {}
    }, 'batch header 2 records per ORI-incident number' => {
        description => 'Batch number 2 or 3 (b2) in a group of records with a common ORI and incident number',
        position => 36,
        width => 3,
        possibilities => {}
    }, 'batch header 3 records per ORI-incident number' => {
        description => 'Batch number 3 of 4 (b3) in a group of records with a common ORI and incident number',
        position => 39,
        width => 3,
        possibilities => {}
    }, 'administrative segment (01) records per ORI-incident number' => {
        description => 'The number of administration segment (01) records in a group of records with a common ORI and incident number',
        position => 42,
        width => 3,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'offense segment (02) records per ORI-incident number' => {
        description => 'The number of offense segment (02) records in a group of records with a common ORI and incident number',
        position => 45,
        width => 3,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'property segment (03) records per ORI-incident number' => {
        description => 'The number of property segment (03) records in a group of records with a common ORI and incident number',
        position => 48,
        width => 3,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'victim segment (04) records per ORI-incident number' => {
        description => 'The number of victim segment (04) records in a group of records with a common ORI and incident number',
        position => 51,
        width => 3,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'offender segment (05) records per ORI-incident number' => {
        description => 'The number of offender segment (05) records in a group of records with a common ORI and incident number',
        position => 54,
        width => 3,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'arrestee segment (06) records per ORI-incident number' => {
        description => 'The number of arrestee segment (06) records in a group of records with a common ORI and incident number',
        position => 57,
        width => 3,
        possibilities => $common_labels->{'-8 and -5'}
    }, 'date ORI was added or was updated by UCR staff' => {
        description => 'YYYYMMDD date that the UCR ORI was added or had an update performed by UCR staff',
        position => 60,
        width => 8,
        possibilities => {}
    }, 'date ORI was entered into NIBRS' => {
        description => 'YYYYMMDD date that the ORI first began submitting incident-based data to the FBI',
        position => 68,
        width => 8,
        possibilities => $common_labels->{'not applicable'}
    }, 'city name' => {
        description => 'This in the city in which the ORI is associated',
        position => 76,
        width => 30,
        possibilities => {}
    }, 'state abbreviation' => {
        description => 'Two-letter abbreviation for the state; can also be determined from state code, index 0',
        position => 106,
        width => 2,
        possibilities => {}
    }, 'population group' => {
        description => 'Shows the population covered by the ORI. Group 0 is possessions; 1-7 are cities; 8-9 are counties.  All populations are inclusive',
        position => 108,
        width => 2,
        possibilities => {
            '0' => 'Possessions',
            '10' => 'Cities 250,000+',
            '11' => 'Cities 1,000,000+',
            '12' => 'Cities 500,000-999,999',
            '13' => 'Cities 250,000-499,999',
            '20' => 'Cities 100,000-249,999',
            '30' => 'Cities 50,000-99,999',
            '40' => 'Cities 25,000-49,999',
            '50' => 'Cities 10,000-24,999',
            '60' => 'Cities 2,500-9,999',
            '70' => 'Cities less than 2,500',
            '80' => 'Non-MSA Counties',
            '81' => 'Non-MSA Counties 100,000+',
            '82' => 'Non-MSA Counties 25,000-99,999',
            '83' => 'Non-MSA Counties 10,000-24,999',
            '84' => 'Non-MSA Counties less than 10,000',
            '85' => 'Non-MSA State Police',
            '90' => 'MSA Counties',
            '91' => 'MSA Counties 100,000+',
            '92' => 'MSA Counties 25,000-99,999',
            '93' => 'MSA Counties 10,000-24,999',
            '94' => 'MSA Counties less than 10,000',
            '95' => 'MSA State Police'
        }
    }, 'country division' => {
        description => 'Geographic division in which the state is located',
        position => 110,
        width => 2,
        possibilities => {
            '0' => 'Possessions',
            '1' => 'New England',
            '2' => 'Middle Atlantic',
            '3' => 'East North Central',
            '4' => 'West North Central',
            '5' => 'South Atlantic',
            '6' => 'East South Central',
            '7' => 'West South Central',
            '8' => 'Mountain',
            '9' => 'Pacific'
        }
    }, 'country region' => {
        desription => 'Geographic region in which the country division is located',
        position => 112,
        width => 2,
        possibilities => {
            '1' => 'North East',
            '2' => 'North Central',
            '3' => 'South',
            '4' => 'West'
        }
    }, 'agency indicator' => {
        description => 'Distinguishes counties and colleges and universities from cities',
        position => 114,
        width => 2,
        possibilities => {
            '0' => 'Covered by another agency',
            '1' => 'City',
            '2' => 'County',
            '3' => 'University or College',
            '4' => 'State Police',
            '5' => 'Special Agency',
            '6' => 'Other state agencies',
            '7' => 'Tribal agencies',
            '8' => 'Federal agencies'
        }
    }, 'core city' => {
        description => 'Designates if the agency is the central city of a Metropolitan Statistical Area (MSA)',
        position => 116,
        width => 2,
        possibilities => $common_labels->{'yes or no'}
    }, 'covered by ORI' => {
        description => 'The ORI of the agency that submits crime data for the agency represented by the batch header.  For example, a county can submit a return which includes the crime data for a city within that county.  This field is blank if the agency is not a "covered-by"',
        position => 118,
        width => 9,
        possibilities => $common_labels->{'not applicable'}
    }, 'FBI field office ID' => {
        description => 'Four digit numeric code for the FBI field office whose territory covers the agency',
        position => 127,
        width => 4,
        possibilities => {
            '9999' => 'Blanked'
        }
    }, 'judicial district' => {
        description => 'The code of the judicial district in which the agency is located.  It is a three digit numeric code followed by a letter that designates the region within the state',
        position => 131,
        width => 4,
        possibilities => $common_labels->{'not applicable'}
    }, 'agency NIBRS flag' => {
        description => 'Designates whether the ORI in a state is an active NIBRS agency or does not yet participate',
        position => 135,
        width => 2,
        possibilities => {
            '0' => 'Does not yet participate',
            '1' => 'Active'
        }
    }, 'agency inactive date' => {
        description => 'YYYYMMDD date that the agency stopped submitting either NIBRS or Summary-Based data directly to the FBI',
        position => 137,
        width => 8,
        possibilities => $common_labels->{'not applicable'}
    }, 'current population 1' => {
        description => 'Population for the agency or the population of the portion of the agency which is located in the county.  Some agencies are in as many a five different counties'
        position => 145,
        width => 9,
        possibilities => {}
    }, 'UCR county code 1' => {
        description => 'The UCR county code for the agency or the UCR county code for the portion of the agency which is located in the county.  Some agencies are in as many as five different counties',
        position => 154,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'MSA code 1' => {
        description => 'The code of the Metropolitan Statistical Area (MSA) in which the agency is located',
        position => 157,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'last population 1' => {
        description => 'The population of the agency in the previous census',
        position => 160,
        width => 9,
        possibilities => {}
    }, 'current population 2' => {
        description => 'Population for the agency or the population of the portion of the agency which is located in the county',
        position => 169,
        width => 9,
        possibilities => {}
    }, 'UCR county code 2' => {
        description => 'The UCR county code for the agency or the UCR county code for the portion of the agency which is located in the county',
        position => 178,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'MSA code 2' => {
        description => 'The code of the Metropolitan Statistical Area (MSA) in which the agency is located',
        position => 181,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'last population 2' => {
        description => 'The population of the agency in the previous census',
        position => 184,
        width => 9,
        possibilities => {}
    }, 'current population 3' => {
        description => 'Population for the agency or the population of the portion of the agency which is located in the county',
        position => 193,
        width => 9,
        possibilities => {}
    }, 'UCR county code 3' => {
        description => 'The UCR county code for the agency or the UCR county code for the portion of the agency which is located in the county',
        position => 202,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'MSA code 3' => {
        description => 'The code of the Metropolitan Statistical Area (MSA) in which the agency is located',
        position => 205,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'last population 3' => {
        description => 'The population of the agency in the previous census',
        position => 208,
        width => 9,
        possibilities => {}
    }, 'current population 4' => {
        description => 'Population for the agency or the population of the portion of the agency which is located in the county',
        position => 217,
        width => 9,
        possibilities => {}
    }, 'UCR county code 4' => {
        description => 'The UCR county code for the agency or the UCR county code for the portion of the agency which is located in the county',
        position => 226,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'MSA code 4' => {
        description => 'The code of the Metropolitan Statistical Area (MSA) in which the agency is located',
        position => 229,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'last population 4' => {
        description => 'The population of the agency in the previous census',
        position => 232,
        width => 9,
        possibilities => {}
    }, 'current population 5' => {
        description => 'Population for the agency or the population of the portion of the agency which is located in the county',
        position => 241,
        width => 9,
        possibilities => {}
    }, 'UCR county code 5' => {
        description => 'The UCR county code for the agency or the UCR county code for the portion of the agency which is located in the county',
        position => 250,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'MSA code 5' => {
        description => 'The code of the Metropolitan Statistical Area (MSA) in which the agency is located',
        position => 253,
        width => 3,
        possibilities => $common_labels->{'not applicable'}
    }, 'last population 5' => {
        description => 'The population of the agency in the previous census',
        position => 256,
        width => 9,
        possibilities => {}
    }, '01-06-12 indicator' => {
        description => 'Used by the UCR to indicate if the agency has submitted data for 12 months, for 6 or more months, or 1 or more months.  Reports can then be generated to include only those agencies meeting the designated reporting time period',
        position => 265,
        width => 2,
        possibilities => $common_labels->{'not applicable'}
    }, 'number of months reported' => {
        description => 'Similar to 01-06-12 indicator except that this field contains exact number of months reported',
        position => 267,
        width => 2,
        possibilities => {}
    }, 'master file year' => {
        description => 'The year of the NIBRS master file requested',
        position => 269,
        width => 4,
        possibilities => {}
    }, 'agency activity indicator january' => {
        description => 'Submission activity for the month of january. Activity does not guarantee the preense of incidents following the batch header but the probability of not having incident would be extremely low.  For example, assume agency X submitted a single incident for a month. Then the following month this incident was deleted from the file becaue it was unfounded.  Since there had been activity, the flag will remain 1 to show this important fact. 1st position = Zero report was submitted. 2nd position = Group A or B was submitted. 3rd position = Window record was submitted',
        position => 273,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator february' => {
        description => 'Submission activity for the month of february',
        position => 276,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator march' => {
        description => 'Submission activity for the month of march',
        position => 279,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator april' => {
        description => 'Submission activity for the month of april',
        position => 282,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator may' => {
        description => 'Submission activity for the month of may',
        position => 285,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator june' => {
        description => 'Submission activity for the month of june',
        position => 288,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator july' => {
        description => 'Submission activity for the month of july',
        position => 291,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator august' => {
        description => 'Submission activity for the month of august',
        position => 294,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator september' => {
        description => 'Submission activity for the month of september',
        position => 297,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator october' => {
        description => 'Submission activity for the month of october',
        position => 300,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator november' => {
        description => 'Submission activity for the month of november',
        position => 303,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'agency activity indicator december' => {
        description => 'Submission activity for the month of december',
        position => 306,
        width => 3,
        possibilities => $common_labels->{'submission flags'}
    }, 'FIPS county 1' => {
        description => 'Each relative position of the UCR county code has a corresponding FIPS county code.  The previous group field entitled Five-County Population Coverage contians four fields occurring five times, one of which is the UCR county code',
        position => 309,
        width => 3,
        possibilities => $common_labels->{'FIPS'}
    }, 'FIPS county 2' => {
        description => 'Each relative position of the UCR county code has a corresponding FIPS county code.',
        position => 312,
        width => 3,
        possibilities => $common_labels->{'FIPS'}
    }, 'FIPS county 3' => {
        description => 'Each relative position of the UCR county code has a corresponding FIPS county code.',
        position => 315,
        width => 3,
        possibilities => $common_labels->{'FIPS'}
    }, 'FIPS county 4' => {
        description => 'Each relative position of the UCR county code has a corresponding FIPS county code.',
        position => 318,
        width => 3,
        possibilities => $common_labels->{'FIPS'}
    }, 'FIPS county 5' => {
        description => 'Each relative position of the UCR county code has a corresponding FIPS county code.',
        position => 321,
        width => 3,
        possibilities => $common_labels->{'FIPS'}
    }, 'report date indicator' => {
        description => 'If value is R, incident date is the date the incident was reported. If blank, it is the date the incident occurred, instead',
        position => 324,
        width => 2,
        possibilities => {
            '0' => 'Incident date',
            '1' => 'Report date',
            '-5' => 'NA Window/Grp B Record'
        }
    }, TODO => {
        description => '',
        position => ,
        width => ,
        possibilities => {}
    },
};

exit;
